language: vi_spacy_model
pipeline:
- name: SpacyNLP
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: CRFEntityExtractor
  features:
  - - low
    - title
    - upper
  - - bias
    - low
    - prefix5
    - prefix2
    - suffix5
    - suffix3
    - suffix2
    - upper
    - title
    - digit
    - pattern
  - - low
    - title
    - upper
- name: EntitySynonymMapper
- name: intent_featurizer_count_vectors
- name: intent_classifier_tensorflow_embedding
- name: ResponseSelector
policies:
- name: MemoizationPolicy
  max_history: 3
- name: KerasPolicy
- name: MappingPolicy
